"""Typed contracts shared by all bricks (SPEC §3, §53 Phase 1)."""

from nomadicos.contracts.action import (
    MODEL_AUTHORITY_FIELDS,
    ActionProposal,
    AuthorizationGrant,
    AuthorizedAction,
    CapabilityRef,
    CompletionClaim,
    ProposalKind,
)
from nomadicos.contracts.benchmark import (
    BenchmarkCategory,
    BenchmarkRecord,
    BenchmarkTask,
    WorkerCriticIterationRecord,
)
from nomadicos.contracts.core import (
    Contract,
    FailureRecord,
    Goal,
    GoalPredicate,
    LogicalOp,
    Plan,
    PlanStep,
    Predicate,
    PredicateGroup,
    TaskStatus,
    parse_predicate,
)
from nomadicos.contracts.execution import (
    ExecutionResult,
    ExecutionStatus,
    Observation,
    ObservationKind,
)
from nomadicos.contracts.memory import (
    MemoryKind,
    MemoryProvenance,
    MemoryQuery,
    MemoryRecord,
    ObjectRecord,
    RelationRecord,
    RetrievedMemory,
)
from nomadicos.contracts.model import (
    CapabilityTag,
    MetricsBundle,
    ModelHealth,
    ModelMetrics,
    ModelRecord,
    TaskRequirements,
    TaskType,
)
from nomadicos.contracts.verification import (
    ClaimState,
    CriticDecision,
    CriticReport,
    EvidenceItem,
    VerificationLevel,
    VerificationResult,
)

__all__ = [
    "MODEL_AUTHORITY_FIELDS",
    "ActionProposal",
    "AuthorizedAction",
    "AuthorizationGrant",
    "BenchmarkCategory",
    "BenchmarkRecord",
    "BenchmarkTask",
    "CapabilityRef",
    "CapabilityTag",
    "ClaimState",
    "CompletionClaim",
    "Contract",
    "CriticDecision",
    "CriticReport",
    "EvidenceItem",
    "ExecutionResult",
    "ExecutionStatus",
    "FailureRecord",
    "Goal",
    "GoalPredicate",
    "LogicalOp",
    "MemoryKind",
    "MemoryProvenance",
    "MemoryQuery",
    "MemoryRecord",
    "MetricsBundle",
    "ModelHealth",
    "ModelMetrics",
    "ModelRecord",
    "ObjectRecord",
    "Observation",
    "ObservationKind",
    "Plan",
    "PlanStep",
    "Predicate",
    "PredicateGroup",
    "ProposalKind",
    "RelationRecord",
    "RetrievedMemory",
    "TaskRequirements",
    "TaskStatus",
    "TaskType",
    "VerificationLevel",
    "VerificationResult",
    "WorkerCriticIterationRecord",
    "parse_predicate",
]
